/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package MenuAD;

import Control.EmpleadoControl;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;

public class UsuariosReg extends javax.swing.JInternalFrame {

    private final EmpleadoControl ControlEmp;
    private String accion;
    public int Pag, Totpag;
    private int totalPorPagina = 10;
    private int numPagina = 1;
    private boolean primeraCarga = true;
    private int totalRegistros;
    private boolean verificc, verificp;

    public UsuariosReg() {
        initComponents();
        TxtVerific.setVisible(false);
        this.ControlEmp = new EmpleadoControl();
        TabGeneral.setEnabledAt(0, true);
        TabGeneral.setEnabledAt(1, false);
        TabGeneral.setSelectedIndex(0);
        Pag = 0;
        Totpag = 10;
    }

    private void paginar() {
        int totalPaginas;

        this.totalRegistros = this.ControlEmp.Total();
        this.totalPorPagina = Integer.parseInt((String) cboTotalPorPagina.getSelectedItem());
        totalPaginas = (int) (Math.ceil((double) this.totalRegistros / this.totalPorPagina));
        if (totalPaginas == 0) {
            totalPaginas = 1;
        }
        cboNumPagina.removeAllItems();

        for (int i = 1; i <= totalPaginas; i++) {
            cboNumPagina.addItem(Integer.toString(i));
        }
        cboNumPagina.setSelectedIndex(0);
    }

    private void listar(String texto, boolean paginar) {
        this.totalPorPagina = Integer.parseInt((String) cboTotalPorPagina.getSelectedItem());
        if ((String) cboNumPagina.getSelectedItem() != null) {
            this.numPagina = Integer.parseInt((String) cboNumPagina.getSelectedItem());
        }

        if (paginar == true) {
            TablaListado.setModel(this.ControlEmp.listar(texto, this.totalPorPagina, this.numPagina));
        } else {
            TablaListado.setModel(this.ControlEmp.listar(texto, this.totalPorPagina, 1));
        }
        TableRowSorter orden = new TableRowSorter(TablaListado.getModel());
        TablaListado.setRowSorter(orden);
        //this.ocultarColumnas();
        LblRegistros.setText("Mostrando " + this.ControlEmp.TotalMostrados() + " de un total de " + this.ControlEmp.Total() + " registros");

    }

    /* public void listar(String Texto) {

        TablaListado.setModel(this.ControlEmp.listar(Texto,Pag,Totpag));
        LblRegistros.setText("Mostrando " + this.ControlEmp.TotalMostrados() + " de un total de " + this.ControlEmp.Total() + " registros.");
    }*/

    private void limpiar() {
        TxtBuscar.setText("");
        TxtNom.setText("");
        txtApellido.setText("");
        TxtFech.setText("");
        TxtCalle.setText("");
        TxtColonia.setText("");
        TxtNumExt.setText("");
        CmbCiudad.setSelectedIndex(0);
        TxtCodP.setText("");
        CmbMunicipio.setSelectedIndex(0);
        CmbEstado.setSelectedIndex(0);
        TxtCel.setText("");
        TxtCE.setText("Correo Electrónico");
        CmbRol.setSelectedIndex(0);
        PSW.setText("");
        VerificacionPSW.setText("");
        LblVerific.setText("");
        ComID.removeAllItems();
        this.accion = "Eliminar";
    }

    public void mensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Sistema", JOptionPane.ERROR_MESSAGE);
    }

    public void mensajeOkey(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Sistema", JOptionPane.INFORMATION_MESSAGE);
    }
    
    public boolean verificar_email(String text){
        
        Pattern emailspatron= Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"+"[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$");
        Matcher MatE=emailspatron.matcher(text);
        return MatE.find();
    }
    public boolean verificar_Passw(String text){
        
        Pattern Passwpatron= Pattern.compile("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{1,8}$");
        Matcher MatP=Passwpatron.matcher(text);
        return MatP.find();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabGeneral = new javax.swing.JTabbedPane();
        Panel_buscador = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaListado = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        TxtBuscar = new javax.swing.JTextField();
        lblNomEmpleado = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnActivar = new javax.swing.JButton();
        btnDesactivar = new javax.swing.JButton();
        LblRegistros = new javax.swing.JLabel();
        BtnNext = new javax.swing.JButton();
        BtnAnt = new javax.swing.JButton();
        cboNumPagina = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cboTotalPorPagina = new javax.swing.JComboBox<>();
        Panel_Registrar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        TxtNom = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtFech = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TxtCalle = new javax.swing.JTextField();
        TxtColonia = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        TxtCel = new javax.swing.JTextField();
        LblCE = new javax.swing.JLabel();
        TxtCE = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        btnGen = new javax.swing.JButton();
        btnCancelar3 = new javax.swing.JButton();
        TxtCodP = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        TxtNumExt = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ComID = new javax.swing.JComboBox<>();
        LblIdEmp = new javax.swing.JLabel();
        Rol = new javax.swing.JLabel();
        CmbRol = new javax.swing.JComboBox<>();
        CmbEstado = new javax.swing.JComboBox<>();
        CmbCiudad = new javax.swing.JComboBox<>();
        CmbMunicipio = new javax.swing.JComboBox<>();
        CmbEstatus = new javax.swing.JComboBox<>();
        Rol1 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        VerificacionPSW = new javax.swing.JPasswordField();
        PSW = new javax.swing.JPasswordField();
        LblVerific = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtVerific = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setVisible(true);

        Panel_buscador.setBackground(new java.awt.Color(153, 255, 255));

        TablaListado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TablaListado.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TablaListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaListado.setCellSelectionEnabled(true);
        TablaListado.setSelectionBackground(new java.awt.Color(102, 255, 255));
        jScrollPane1.setViewportView(TablaListado);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lupa.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        TxtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuscarActionPerformed(evt);
            }
        });
        TxtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtBuscarKeyTyped(evt);
            }
        });

        lblNomEmpleado.setText("Nombre Empleado");

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/añadir.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        btnActualizar.setText("Editar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnActivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Act.png"))); // NOI18N
        btnActivar.setText("Activar");
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });

        btnDesactivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Desac.png"))); // NOI18N
        btnDesactivar.setText("Desactivar");
        btnDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarActionPerformed(evt);
            }
        });

        BtnNext.setText("->");
        BtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNextActionPerformed(evt);
            }
        });

        BtnAnt.setText("<-");
        BtnAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAntActionPerformed(evt);
            }
        });

        cboNumPagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNumPaginaActionPerformed(evt);
            }
        });

        jLabel26.setText("# Página");

        jLabel27.setText("Total de registros por página ");

        cboTotalPorPagina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "50", "100", "200", "500" }));
        cboTotalPorPagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTotalPorPaginaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_buscadorLayout = new javax.swing.GroupLayout(Panel_buscador);
        Panel_buscador.setLayout(Panel_buscadorLayout);
        Panel_buscadorLayout.setHorizontalGroup(
            Panel_buscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_buscadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_buscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_buscadorLayout.createSequentialGroup()
                        .addGroup(Panel_buscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomEmpleado)
                            .addGroup(Panel_buscadorLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNuevo)
                                .addGap(9, 9, 9)
                                .addComponent(btnActualizar)))
                        .addGap(190, 190, 190))
                    .addGroup(Panel_buscadorLayout.createSequentialGroup()
                        .addGroup(Panel_buscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_buscadorLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(47, 47, 47)
                                .addComponent(cboNumPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(jLabel27)
                                .addGap(35, 35, 35)
                                .addComponent(cboTotalPorPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(188, 188, 188)
                                .addComponent(LblRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(Panel_buscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_buscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnDesactivar, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnActivar))
                    .addGroup(Panel_buscadorLayout.createSequentialGroup()
                        .addComponent(BtnAnt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        Panel_buscadorLayout.setVerticalGroup(
            Panel_buscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_buscadorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblNomEmpleado)
                .addGap(4, 4, 4)
                .addGroup(Panel_buscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_buscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnActualizar)
                        .addComponent(btnNuevo))
                    .addComponent(btnBuscar)
                    .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(Panel_buscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_buscadorLayout.createSequentialGroup()
                        .addComponent(btnActivar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDesactivar)
                        .addGap(18, 18, 18)
                        .addGroup(Panel_buscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnAnt)
                            .addComponent(BtnNext))
                        .addGap(67, 67, 67)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_buscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_buscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboNumPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboTotalPorPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26)
                        .addComponent(jLabel27))
                    .addComponent(LblRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        TabGeneral.addTab("Empleados", Panel_buscador);

        Panel_Registrar.setBackground(new java.awt.Color(153, 255, 255));
        Panel_Registrar.setFocusCycleRoot(true);

        jLabel13.setText("Nombres");

        TxtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomActionPerformed(evt);
            }
        });
        TxtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNomKeyTyped(evt);
            }
        });

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });

        jLabel14.setText("Apellidos");

        TxtFech.setText("YYYY/MM/DD");
        TxtFech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFechActionPerformed(evt);
            }
        });
        TxtFech.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtFechKeyTyped(evt);
            }
        });

        jLabel15.setText("Fecha de nacimiento");

        jLabel16.setText("Calle");

        TxtCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCalleActionPerformed(evt);
            }
        });
        TxtCalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCalleKeyTyped(evt);
            }
        });

        TxtColonia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtColoniaKeyTyped(evt);
            }
        });

        jLabel17.setText("Colonia");

        jLabel18.setText("Ciudad");

        jLabel19.setText("Municipio");

        jLabel22.setText("Celular");

        TxtCel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCelKeyTyped(evt);
            }
        });

        LblCE.setText("Correo Electrónico");

        TxtCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCEActionPerformed(evt);
            }
        });
        TxtCE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCEKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCEKeyTyped(evt);
            }
        });

        jLabel25.setText("Contraseña");

        btnGen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        btnGen.setText("Registrar");
        btnGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenActionPerformed(evt);
            }
        });

        btnCancelar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btnCancelar3.setText("Cancelar");
        btnCancelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar3ActionPerformed(evt);
            }
        });

        TxtCodP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodPActionPerformed(evt);
            }
        });
        TxtCodP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCodPKeyTyped(evt);
            }
        });

        jLabel41.setText("Codigo Postal");

        TxtNumExt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNumExtKeyTyped(evt);
            }
        });

        jLabel42.setText("Número exterior");

        jLabel20.setText("Estado");

        ComID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComIDActionPerformed(evt);
            }
        });

        LblIdEmp.setText("Empleado ID");

        Rol.setText("Rol");

        CmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un Rol", "Administrador", "Prestamista" }));
        CmbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbRolActionPerformed(evt);
            }
        });

        CmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un estado", "Sinaloa" }));
        CmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbEstadoActionPerformed(evt);
            }
        });

        CmbCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una ciudad", "Ahome", "Angostura", "Badiragiuato", "Choix", "Concordia", "Copala", "Cosalá", "Culiacan", "Dimas", "Elota", "El Fuerte", "El Rosario", "Escuinapa", "Guamúchil", "Guasave", "La Cruz", "Los Mochis", "Mazatlan", "Mocorito", "Novalto", "San Ignacio", "Sinaloa de Leyva", "Topolobampo", "Vado Hondo" }));
        CmbCiudad.setToolTipText("");

        CmbMunicipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un municipio", "Ahome", "Angostura", "Badiraguato", "Concordia", "Cosalá", "Culiacán", "Choix", "Elota", "Escuinapa", "El Fuerte", "Guasave", "Mazatlán", "Mocorito", "Rosario", "Salvador Alvarado", "San Ignacio", "Sinaloa", "Novalto" }));

        CmbEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona El estatus", "Laborando", "Despedido" }));
        CmbEstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbEstatusActionPerformed(evt);
            }
        });

        Rol1.setText("Estatus");

        jLabel28.setText("Repetir Contraseña");

        VerificacionPSW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificacionPSWActionPerformed(evt);
            }
        });
        VerificacionPSW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                VerificacionPSWKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                VerificacionPSWKeyTyped(evt);
            }
        });

        PSW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSWActionPerformed(evt);
            }
        });
        PSW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PSWKeyReleased(evt);
            }
        });

        TxtVerific.setBackground(new java.awt.Color(153, 255, 255));
        TxtVerific.setColumns(20);
        TxtVerific.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtVerific.setRows(8);
        TxtVerific.setTabSize(5);
        TxtVerific.setToolTipText("");
        TxtVerific.setCaretColor(new java.awt.Color(102, 255, 255));
        TxtVerific.setDisabledTextColor(new java.awt.Color(102, 255, 255));
        TxtVerific.setDoubleBuffered(true);
        jScrollPane2.setViewportView(TxtVerific);

        javax.swing.GroupLayout Panel_RegistrarLayout = new javax.swing.GroupLayout(Panel_Registrar);
        Panel_Registrar.setLayout(Panel_RegistrarLayout);
        Panel_RegistrarLayout.setHorizontalGroup(
            Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19)
                    .addComponent(CmbMunicipio, 0, 173, Short.MAX_VALUE)
                    .addComponent(TxtCalle)
                    .addComponent(TxtNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                        .addComponent(CmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtCodP, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TxtCel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(764, 764, 764))
                    .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                        .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel20)
                                .addGap(155, 155, 155)
                                .addComponent(jLabel41)
                                .addGap(72, 72, 72)
                                .addComponent(jLabel22))
                            .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                                .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel14))
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                                        .addComponent(jLabel42)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel17)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(TxtFech, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblIdEmp)
                                    .addComponent(ComID, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                                .addComponent(TxtNumExt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(CmbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(833, 833, 833))))
            .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtCE, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblCE, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PSW, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(VerificacionPSW, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblVerific, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                        .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(Rol))
                            .addComponent(btnCancelar3)
                            .addComponent(CmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(Rol1))
                            .addComponent(CmbEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_RegistrarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGen)
                        .addGap(19, 19, 19)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_RegistrarLayout.setVerticalGroup(
            Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(TxtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFech, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                        .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblIdEmp)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                        .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)))
                        .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtNumExt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(0, 0, 0)
                        .addComponent(CmbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                        .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel19))
                            .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel20)))
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_RegistrarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel41))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCodP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                        .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel25)
                            .addComponent(LblCE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtCE, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PSW, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VerificacionPSW, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblVerific, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                        .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                                .addComponent(Rol)
                                .addGap(14, 14, 14)
                                .addComponent(CmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_RegistrarLayout.createSequentialGroup()
                                .addComponent(Rol1)
                                .addGap(14, 14, 14)
                                .addComponent(CmbEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(Panel_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGen)
                            .addComponent(btnCancelar3))))
                .addContainerGap(253, Short.MAX_VALUE))
        );

        TabGeneral.addTab("Registrar", Panel_Registrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabGeneral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabGeneral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCodPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodPActionPerformed

    private void btnCancelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar3ActionPerformed
        TabGeneral.setEnabledAt(1, false);
        TabGeneral.setEnabledAt(0, true);
        TabGeneral.setSelectedIndex(0);
        limpiar();
    }//GEN-LAST:event_btnCancelar3ActionPerformed

    private void btnGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenActionPerformed

        if (TxtNom.getText().length() == 0 || TxtNom.getText().length() > 70) {
            JOptionPane.showMessageDialog(this, "Debes ingresar un Nombre y no debe ser mayor a 70 caracteres, es obligatorio", "Nombre", JOptionPane.WARNING_MESSAGE);
            TxtNom.requestFocus();
            return;
        }
        if (txtApellido.getText().length() == 0 || txtApellido.getText().length() > 30) {
            JOptionPane.showMessageDialog(this, "Debes ingresar un Apellido y no debe ser mayor a 30 caracteres, es obligatorio", "Apellido", JOptionPane.WARNING_MESSAGE);
            txtApellido.requestFocus();
            return;
        }
        if (TxtFech.getText().length() == 0 || TxtFech.getText().length() > 12) {
            JOptionPane.showMessageDialog(this, "Debes ingresar una Fecha de nacimiento, es obligatorio", "Fecha", JOptionPane.WARNING_MESSAGE);
            TxtFech.requestFocus();
            return;
        }
        if (TxtCalle.getText().length() == 0 || TxtCalle.getText().length() > 50) {
            JOptionPane.showMessageDialog(this, "Debes ingresar una calle y no debe ser mayor a 50 caracteres, es obligatorio", "Calle", JOptionPane.WARNING_MESSAGE);
            TxtCalle.requestFocus();
            return;
        }
        if (TxtNumExt.getText().length() == 0 || TxtNumExt.getText().length() > 8) {
            JOptionPane.showMessageDialog(this, "Debes ingresar un Número exterior y no debe ser mayor a 8 caracteres, es obligatorio", "Número exterior", JOptionPane.WARNING_MESSAGE);
            TxtNumExt.requestFocus();
            return;
        }
        if (TxtColonia.getText().length() == 0 || TxtColonia.getText().length() > 60) {
            JOptionPane.showMessageDialog(this, "Debes ingresar una Colonia y no debe ser mayor a 40 caracteres, es obligatorio", "Colonia", JOptionPane.WARNING_MESSAGE);
            TxtColonia.requestFocus();
            return;
        }
        if (TxtCodP.getText().length() == 0 || TxtCodP.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Debes ingresar un Código Postal y no debe ser mayor a 5 caracteres, es obligatorio", "Código Postal", JOptionPane.WARNING_MESSAGE);
            TxtCodP.requestFocus();
            return;
        }
        if (TxtCel.getText().length() == 0 || TxtCel.getText().length() > 10) {
            JOptionPane.showMessageDialog(this, "Debes ingresar un Télefono y no debe ser mayor a 10 caracteres, es obligatorio", "Celular", JOptionPane.WARNING_MESSAGE);
            TxtCel.requestFocus();
            return;
        }
        if (TxtCE.getText().length() == 0 || TxtCE.getText().length() > 70) {
            JOptionPane.showMessageDialog(this, "Debes ingresar un correo y no debe ser mayor a 30 caracteres, es obligatorio", "Correo Electrónico", JOptionPane.WARNING_MESSAGE);
            TxtCE.requestFocus();
            return;
        }
        if (PSW.getText().length() == 0 || PSW.getText().length() > 30) {
            JOptionPane.showMessageDialog(this, "Debes ingresar una Contraseña, es obligatorio", "Contraseña", JOptionPane.WARNING_MESSAGE);
            PSW.requestFocus();
            return;
        }
        if (CmbEstado.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un Estado", "Estado", JOptionPane.WARNING_MESSAGE);
            CmbEstado.requestFocus();
            return;
        }
        if (CmbCiudad.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar una Ciudad", "Ciudad", JOptionPane.WARNING_MESSAGE);
            CmbCiudad.requestFocus();
            return;
        }
        if (CmbMunicipio.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un Municipio", "Municipio", JOptionPane.WARNING_MESSAGE);
            CmbMunicipio.requestFocus();
            return;
        }
        if (CmbRol.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un Rol", "Rol", JOptionPane.WARNING_MESSAGE);
            CmbRol.requestFocus();
            return;
        }
        if (CmbEstatus.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un Estatus", "Estatus", JOptionPane.WARNING_MESSAGE);
            CmbEstatus.requestFocus();
            return;
        }
        
        /*String CE = "", pasword = "", mensaje = "";
        if (matcher.matches()) {
            LblCE.setText("Correo Electronico Valido");
            LblCE.setForeground(Color.green);
            CE = TxtCE.getText();
        } else if(!matcher.matches()){
            LblCE.setText("Correo Electronico No valido");
            LblCE.setForeground(Color.red);
            TxtCE.requestFocus();
            CE = "";
            return;
        }
        if (PSW.getText().equals(VerificacionPSW.getText())) {
            if (pswmatcher.matches()) {
                pasword = PSW.getText();
            } else {
                mensaje = "La contraseña debe contener al menos \n 1 Núnmero del 0 al 9 \n una Mayuscula \n una Minuscula \n Un caracter especial como: !#$%& \n Ser de al menos 8 digitos";
                JOptionPane.showMessageDialog(this, mensaje, "Contraseña error", JOptionPane.WARNING_MESSAGE);
                pasword = null;
                return;
            }
        } else {
            LblVerific.setText("Las Contraseñas no coinciden");
            return;
        }*/
        String pasword,CE;
        if(this.verificp == true){
            pasword=PSW.getText();
        }else{
            PSW.requestFocus();
            return;
        }
        if(this.verificc == true){
            CE=TxtCE.getText();
            
        }else{
            TxtCE.requestFocus();
            return;
        }
        String respemp;
        int id;
        boolean Estatus = false;
        //registro
        if (CmbRol.getSelectedItem().equals("Prestamista")) {
            id = 2;
        } else {
            id = 1;
        }
        switch (CmbRol.getSelectedIndex()) {
            case 1 ->
                Estatus = true;
            case 2 ->
                Estatus = false;
            default -> {
                if (CmbEstatus.getSelectedIndex() <= 0) {
                    JOptionPane.showMessageDialog(this, "Debes seleccionar un Estatus", "Estatus", JOptionPane.WARNING_MESSAGE);
                    CmbEstatus.requestFocus();
                    return;
                }
            }
        }
        if (this.accion.equals("Registrar")) {
            //registrar
            respemp = this.ControlEmp.Insertar(TxtNom.getText(), txtApellido.getText(),pasword, Estatus, TxtFech.getText(), TxtCalle.getText(), TxtNumExt.getText(), TxtColonia.getText(), String.valueOf(CmbCiudad.getSelectedItem()), TxtCodP.getText(), String.valueOf(CmbMunicipio.getSelectedItem()), String.valueOf(CmbEstado.getSelectedItem()), CE, TxtCel.getText(), id);
            if (respemp.equals("OK")) {
                this.mensajeOkey("Registrado Correctamente");
                this.limpiar();
                this.listar("", false);
                TabGeneral.setEnabledAt(0, true);
                TabGeneral.setEnabledAt(1, false);
                TabGeneral.setSelectedIndex(0);
            } else {
                this.mensajeError(respemp);
            }
        } else {
            //actualizar
            if (this.accion.equals("Actualizar")) {
                respemp = this.ControlEmp.Actualizar(TxtNom.getText(), txtApellido.getText(), pasword, TxtFech.getText(), TxtNom.getText(), TxtCalle.getText(), TxtNumExt.getText(), TxtColonia.getText(), String.valueOf(CmbCiudad.getSelectedItem()), TxtCodP.getText(), String.valueOf(CmbMunicipio.getSelectedItem()), String.valueOf(CmbEstado.getSelectedItem()), CE, TxtCel.getText(), id, Integer.parseInt(String.valueOf(ComID.getSelectedItem())));
                if (respemp.equals("OK")) {
                    this.mensajeOkey("Actualizado Correctamente");
                    this.limpiar();
                    this.listar("", false);
                    TabGeneral.setEnabledAt(0, true);
                    TabGeneral.setEnabledAt(1, false);
                    TabGeneral.setSelectedIndex(0);
                } else {
                    this.mensajeError(respemp);
                }
            }
        }
    }//GEN-LAST:event_btnGenActionPerformed

    private void TxtCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCEActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void TxtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomActionPerformed

    private void BtnAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAntActionPerformed
        if (Pag >= 10 && Totpag >= 10) {
            Pag = Pag - 10;
            Totpag = Totpag - 10;
        } else {
            Pag = 0;
            Totpag = 10;
        }
    }//GEN-LAST:event_BtnAntActionPerformed

    private void BtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNextActionPerformed
        if (Pag <= 0 && Totpag <= 10) {
            Pag = Pag + 10;
            Totpag = Totpag + 10;
        } else {
            Pag = 0;
            Pag = Pag + 10;
            Totpag = Totpag + 10;
        }
    }//GEN-LAST:event_BtnNextActionPerformed

    private void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarActionPerformed
        if (TablaListado.getSelectedRowCount() == 1) {
            int Id = Integer.parseInt(String.valueOf(TablaListado.getValueAt(TablaListado.getSelectedRow(), 0)));
            String nombre = String.valueOf(TablaListado.getValueAt(TablaListado.getSelectedRow(), 1));
            if (JOptionPane.showConfirmDialog(this, "Deseas desactivar el registro: " + nombre + "?", "Desactivar", JOptionPane.YES_NO_OPTION) == 0) {
                String resp = this.ControlEmp.Desactivar(Id);
                if (resp.equals("OK")) {
                    this.mensajeOkey("Registro desactivado");
                    this.listar("", false);
                } else {
                    this.mensajeError(resp);
                }
            } else {
                this.mensajeError("Selecciona 1 registro a desactivar");
            }

        }
    }//GEN-LAST:event_btnDesactivarActionPerformed

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        if (TablaListado.getSelectedRowCount() == 1) {
            int Id = Integer.parseInt(String.valueOf(TablaListado.getValueAt(TablaListado.getSelectedRow(), 0)));
            String nombre = String.valueOf(TablaListado.getValueAt(TablaListado.getSelectedRow(), 1));
            if (JOptionPane.showConfirmDialog(this, "Deseas activar el registro: " + nombre + "?", "Desactivar", JOptionPane.YES_NO_OPTION) == 0) {
                String resp = this.ControlEmp.Activar(Id);
                if (resp.equals("OK")) {
                    this.mensajeOkey("Registro activado");
                    this.listar("", false);
                } else {
                    this.mensajeError(resp);
                }
            } else {
                this.mensajeError("Selecciona 1 registro a activar");
            }

        }
    }//GEN-LAST:event_btnActivarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (TablaListado.getSelectedRowCount() == 1) {
            String id = String.valueOf(TablaListado.getValueAt(TablaListado.getSelectedRow(), 0));
            String Nombre = String.valueOf(TablaListado.getValueAt(TablaListado.getSelectedRow(), 1));
            String Apellido = String.valueOf(TablaListado.getValueAt(TablaListado.getSelectedRow(), 2));
            String Contrasena = String.valueOf(TablaListado.getValueAt(TablaListado.getSelectedRow(), 3));
            String Fecha = String.valueOf(TablaListado.getValueAt(TablaListado.getSelectedRow(), 5));
            String Calle = String.valueOf(TablaListado.getValueAt(TablaListado.getSelectedRow(), 6));
            String NumExt = String.valueOf(TablaListado.getValueAt(TablaListado.getSelectedRow(), 7));
            String Colonia = String.valueOf(TablaListado.getValueAt(TablaListado.getSelectedRow(), 8));
            String Ciudad = String.valueOf(TablaListado.getValueAt(TablaListado.getSelectedRow(), 9));
            String CodP = String.valueOf(TablaListado.getValueAt(TablaListado.getSelectedRow(), 10));
            String Municipio = String.valueOf(TablaListado.getValueAt(TablaListado.getSelectedRow(), 11));
            String Estado = String.valueOf(TablaListado.getValueAt(TablaListado.getSelectedRow(), 12));
            String Email = String.valueOf(TablaListado.getValueAt(TablaListado.getSelectedRow(), 13));
            String Telefono = String.valueOf(TablaListado.getValueAt(TablaListado.getSelectedRow(), 14));
            String Rol_id = String.valueOf(TablaListado.getValueAt(TablaListado.getSelectedRow(), 15));
            String Estatus = String.valueOf(TablaListado.getValueAt(TablaListado.getSelectedRow(), 4));

            /*switch (Rol_id) {
                case "1":
                    CmbRol.setSelectedIndex(1);
                    break;
                case "2":
                    CmbRol.setSelectedIndex(2);
                default:
                    mensajeError("Rol ID no encontrado") ;
            }*/
            if (Rol_id.equals("1")) {
                CmbRol.setSelectedIndex(1);
            } else {
                CmbRol.setSelectedIndex(2);
            }
            if (Estatus.equals("Laborando")) {
                CmbEstatus.setSelectedIndex(1);
            } else {
                CmbEstatus.setSelectedIndex(2);
            }
            ComID.setEditable(false);
            ComID.addItem(id);
            TxtNom.setText(Nombre);
            txtApellido.setText(Apellido);
            VerificacionPSW.setText(Contrasena);
            TxtFech.setText(Fecha);
            ComID.setSelectedItem(id);
            TxtCalle.setText(Calle);
            TxtCel.setText(Telefono);
            CmbCiudad.setSelectedItem(Ciudad);
            TxtColonia.setText(Colonia);
            TxtCodP.setText(CodP);
            PSW.setText(Contrasena);
            CmbEstado.setSelectedItem(Estado);
            CmbMunicipio.setSelectedItem(Municipio);
            TxtNumExt.setText(NumExt);
            TxtCE.setText(Email);
            LblIdEmp.setVisible(true);
            ComID.setVisible(true);

            TabGeneral.setEnabledAt(0, false);
            TabGeneral.setEnabledAt(1, true);
            TabGeneral.setSelectedIndex(1);
            this.accion = "Actualizar";
            btnGen.setText("Actualizar");

        } else {
            this.mensajeError("Seleccione 1 Registro");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        LblIdEmp.setVisible(false);
        ComID.setVisible(false);
        TabGeneral.setEnabledAt(1, true);
        TabGeneral.setEnabledAt(0, false);
        TabGeneral.setSelectedIndex(1);
        this.accion = "Registrar";
        btnGen.setText("Registrar");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void TxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(TxtBuscar.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Debes ingresar un nombre para buscar", "Sistema", JOptionPane.WARNING_MESSAGE);
            TxtBuscar.requestFocus();
            return;
        }
        this.listar(TxtBuscar.getText(), false);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cboNumPaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNumPaginaActionPerformed
        if (this.primeraCarga == false) {
            this.listar("", true);
        }
    }//GEN-LAST:event_cboNumPaginaActionPerformed

    private void cboTotalPorPaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTotalPorPaginaActionPerformed
        this.paginar();
    }//GEN-LAST:event_cboTotalPorPaginaActionPerformed

    private void CmbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbRolActionPerformed

    }//GEN-LAST:event_CmbRolActionPerformed

    private void TxtCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCalleActionPerformed

    private void CmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbEstadoActionPerformed

    private void CmbEstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbEstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbEstatusActionPerformed

    private void ComIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComIDActionPerformed

    }//GEN-LAST:event_ComIDActionPerformed

    private void TxtNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNomKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)) {
            evt.consume();
        }
    }//GEN-LAST:event_TxtNomKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void TxtFechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFechActionPerformed

    private void TxtFechKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtFechKeyTyped

    }//GEN-LAST:event_TxtFechKeyTyped

    private void TxtCalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCalleKeyTyped
        char n = evt.getKeyChar();
        if (n < '0' || n > 'z') {
            evt.consume();

        }
    }//GEN-LAST:event_TxtCalleKeyTyped

    private void TxtNumExtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNumExtKeyTyped
        char n = evt.getKeyChar();
        if (n < '0' || n > 'z') {
            evt.consume();

        }
    }//GEN-LAST:event_TxtNumExtKeyTyped

    private void TxtColoniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtColoniaKeyTyped
        char n = evt.getKeyChar();
        if (n < '0' || n > 'z') {
            evt.consume();

        }
    }//GEN-LAST:event_TxtColoniaKeyTyped

    private void TxtCodPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCodPKeyTyped
        char n = evt.getKeyChar();
        if (n < '0' || n > '9') {
            evt.consume();

        }
    }//GEN-LAST:event_TxtCodPKeyTyped

    private void TxtCelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCelKeyTyped
        char n = evt.getKeyChar();
        if (n < '0' || n > '9') {
            evt.consume();

        }
    }//GEN-LAST:event_TxtCelKeyTyped

    private void TxtCEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCEKeyTyped

    }//GEN-LAST:event_TxtCEKeyTyped

    private void TxtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBuscarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscarKeyTyped

    private void VerificacionPSWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificacionPSWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VerificacionPSWActionPerformed

    private void PSWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PSWActionPerformed

    private void TxtCEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCEKeyReleased
        if (TxtCE.getText().length() > 0) {
            if (verificar_email(TxtCE.getText())) {
                LblVerific.setText("El correo electronico es valido");
                LblVerific.setForeground(Color.GREEN);
                this.verificc = true;

            } else {
                LblVerific.setText("El correo electronico no es valido");
                LblVerific.setForeground(Color.RED);
                this.verificc = false;
            }
        } else {
            LblVerific.setText("");
            this.verificc = false;

        }
    }//GEN-LAST:event_TxtCEKeyReleased

    private void PSWKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PSWKeyReleased
        String Mensaje;

        if (PSW.getText().length() > 0) {
            if (verificar_Passw(PSW.getText())) {
                TxtVerific.setVisible(true);
                TxtVerific.setText("La contrasena es correcta");
                TxtVerific.setForeground(Color.GREEN);
                if (PSW.getText().equals(VerificacionPSW.getText())) {
                    TxtVerific.setText("");
                    TxtVerific.setText("Las Contrasenas Coinciden");
                    TxtVerific.setForeground(Color.GREEN);
                    this.verificp = true;
                } else {
                    TxtVerific.setText("");
                    TxtVerific.setText("Las contrasenas no coinciden");
                    TxtVerific.setForeground(Color.RED);
                }
            } else {
                TxtVerific.setVisible(true);
                TxtVerific.setText("");
                TxtVerific.setForeground(Color.RED);
                Mensaje = "La contraseña debe contener al menos: \n 1 Número del 0 al 9 \n Una Letra Mayúscula Una Minúscula \n Un caracter especial como: !#$%& \n Ser de al menos 8 dígitos";
                TxtVerific.setText(Mensaje);
                
            }
        } else {
            TxtVerific.setVisible(false);
            TxtVerific.setText("");
            this.verificp = false;
        }
    }//GEN-LAST:event_PSWKeyReleased

    private void VerificacionPSWKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VerificacionPSWKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_VerificacionPSWKeyTyped

    private void VerificacionPSWKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VerificacionPSWKeyReleased
        String Mensaje;

        if (PSW.getText().length() > 0) {
            if (verificar_Passw(PSW.getText())) {
                TxtVerific.setVisible(true);
                TxtVerific.setText("La contraseña es correcta");
                TxtVerific.setForeground(Color.GREEN);
                if (VerificacionPSW.getText().equals(PSW.getText())) {
                    TxtVerific.setText("");
                    TxtVerific.setText("Las Contraseñas Coinciden");
                    TxtVerific.setForeground(Color.GREEN);
                } else {
                    TxtVerific.setText("");
                    TxtVerific.setText("Las contraseñas no coinciden");
                    TxtVerific.setForeground(Color.RED);
                }
            } else {
                TxtVerific.setVisible(true);
                TxtVerific.setText("");
                TxtVerific.setForeground(Color.RED);
                Mensaje = "La contraseña debe contener al menos: \n 1 Número del 0 al 9 \n Una Letra Mayúscula Una Minúscula \n Un caracter especial como: !#$%& \n Ser de al menos 8 dígitos";
                TxtVerific.setText(Mensaje);
            }
        } else {
            TxtVerific.setVisible(false);
            TxtVerific.setText("");
        }
    }//GEN-LAST:event_VerificacionPSWKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnt;
    private javax.swing.JButton BtnNext;
    private javax.swing.JComboBox<String> CmbCiudad;
    private javax.swing.JComboBox<String> CmbEstado;
    private javax.swing.JComboBox<String> CmbEstatus;
    private javax.swing.JComboBox<String> CmbMunicipio;
    private javax.swing.JComboBox<String> CmbRol;
    private javax.swing.JComboBox<String> ComID;
    private javax.swing.JLabel LblCE;
    private javax.swing.JLabel LblIdEmp;
    private javax.swing.JLabel LblRegistros;
    private javax.swing.JLabel LblVerific;
    private javax.swing.JPasswordField PSW;
    private javax.swing.JPanel Panel_Registrar;
    private javax.swing.JPanel Panel_buscador;
    private javax.swing.JLabel Rol;
    private javax.swing.JLabel Rol1;
    private javax.swing.JTabbedPane TabGeneral;
    private javax.swing.JTable TablaListado;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JTextField TxtCE;
    private javax.swing.JTextField TxtCalle;
    private javax.swing.JTextField TxtCel;
    private javax.swing.JTextField TxtCodP;
    private javax.swing.JTextField TxtColonia;
    private javax.swing.JTextField TxtFech;
    private javax.swing.JTextField TxtNom;
    private javax.swing.JTextField TxtNumExt;
    private javax.swing.JTextArea TxtVerific;
    private javax.swing.JPasswordField VerificacionPSW;
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar3;
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JButton btnGen;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cboNumPagina;
    private javax.swing.JComboBox<String> cboTotalPorPagina;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNomEmpleado;
    private javax.swing.JTextField txtApellido;
    // End of variables declaration//GEN-END:variables
}
