/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package MenuAD;

import Control.ContratoADControl;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author CHRISTOPHERURIELTAFO
 */
public class Validacion extends javax.swing.JInternalFrame {
    
    private  final ContratoADControl CONTROLCONTR;
    public Validacion() {
        initComponents();
        this.CONTROLCONTR = new ContratoADControl();
    }
    
    public void listar(int id) {

        ContratoTabla.setModel(this.CONTROLCONTR.listar(id));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPan = new javax.swing.JPanel();
        TxtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAuto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ContratoTabla = new javax.swing.JTable();
        btnNeg = new javax.swing.JButton();
        btnArch = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        JPan.setBackground(new java.awt.Color(102, 255, 255));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lupa.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAuto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Autorizacion.png"))); // NOI18N
        btnAuto.setText("Autorizar");
        btnAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoActionPerformed(evt);
            }
        });

        ContratoTabla.setBackground(new java.awt.Color(153, 255, 255));
        ContratoTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(ContratoTabla);

        btnNeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btnNeg.setText("Negar");
        btnNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegActionPerformed(evt);
            }
        });

        btnArch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sesion.png"))); // NOI18N
        btnArch.setText("Archivo");
        btnArch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanLayout = new javax.swing.GroupLayout(JPan);
        JPan.setLayout(JPanLayout);
        JPanLayout.setHorizontalGroup(
            JPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPanLayout.createSequentialGroup()
                        .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAuto)
                        .addGap(18, 18, 18)
                        .addComponent(btnNeg))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnArch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanLayout.setVerticalGroup(
            JPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(JPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAuto)
                        .addComponent(btnNeg))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArch))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(TxtBuscar.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Debes ingresar un nombre para buscar", "Sistema", JOptionPane.WARNING_MESSAGE);
            TxtBuscar.requestFocus();
            return;
        }
        this.listar(Integer.parseInt(TxtBuscar.getText()));
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoActionPerformed
        if (ContratoTabla.getSelectedRowCount() == 1) {
            int id = Integer.parseInt(String.valueOf(ContratoTabla.getValueAt(ContratoTabla.getSelectedRow(), 0)));
            this.CONTROLCONTR.Validar(id);
        }else{
            ContratoTabla.requestFocus();
            JOptionPane.showMessageDialog(this,"Favor de seleccionar un registro","Tabla Contrato",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAutoActionPerformed

    private void btnNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegActionPerformed
        if (ContratoTabla.getSelectedRowCount() == 1) {
            int id = Integer.parseInt(String.valueOf(ContratoTabla.getValueAt(ContratoTabla.getSelectedRow(), 0)));
            this.CONTROLCONTR.Validar(id);
        }else{
            ContratoTabla.requestFocus();
            JOptionPane.showMessageDialog(this,"Favor de seleccionar un registro","Tabla Contrato",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnNegActionPerformed

    private void btnArchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchActionPerformed
       if (ContratoTabla.getSelectedRowCount() == 1) {
            String ruta = String.valueOf(ContratoTabla.getValueAt(ContratoTabla.getSelectedRow(), 4));
            try{
                Runtime.getRuntime().exec("cmd /c start "+ ruta);
            }catch(IOException e){
                e.printStackTrace();
            }
        }else{
            ContratoTabla.requestFocus();
            JOptionPane.showMessageDialog(this,"Favor de seleccionar un registro","Tabla Contrato",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnArchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ContratoTabla;
    private javax.swing.JPanel JPan;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JButton btnArch;
    private javax.swing.JButton btnAuto;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNeg;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
